// 14.1

// function testError(number) {
//   if (number % 2 === 0) {
//     throw Error('please enter odd number');
//   } else {
//     console.log('your number is: ', number);
//   }
// }

// testError(3);
// testError(2);

// 14.2
// 14.2.1
// function throwIt(exception) {
//   try {
//     throw exception;
//   } catch (e) {
//     console.log('Caught' + e);
//   }
// }

// throwIt(3);
// throwIt('hello');
// throwIt(new Error('An error happened'));

// 14.3
console.log(new Array(-1));
